# Generated by Django 4.2.2 on 2023-06-19 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_parks', '0001_initial'),
        ('cars', '0003_carmodel_delete_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='body_type',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='engine_volume',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='seat_count',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='auto_park',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auto_parks.autoparkmodel'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
